<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PelanggaransTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pelanggarans')->delete();
        
        \DB::table('pelanggarans')->insert(array (
            0 => 
            array (
                'id_pelanggaran' => 27,
                'id_siswa' => 1845,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:33:41',
            ),
            1 => 
            array (
                'id_pelanggaran' => 28,
                'id_siswa' => 1845,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:33:41',
            ),
            2 => 
            array (
                'id_pelanggaran' => 29,
                'id_siswa' => 1846,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:38:25',
            ),
            3 => 
            array (
                'id_pelanggaran' => 30,
                'id_siswa' => 1847,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:38:42',
            ),
            4 => 
            array (
                'id_pelanggaran' => 31,
                'id_siswa' => 1847,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:38:43',
            ),
            5 => 
            array (
                'id_pelanggaran' => 32,
                'id_siswa' => 1847,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Tidak bawa buku',
                'poin' => 2,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:38:43',
            ),
            6 => 
            array (
                'id_pelanggaran' => 33,
                'id_siswa' => 1848,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:39:06',
            ),
            7 => 
            array (
                'id_pelanggaran' => 34,
                'id_siswa' => 1848,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:39:06',
            ),
            8 => 
            array (
                'id_pelanggaran' => 35,
                'id_siswa' => 1848,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Tidak bawa buku',
                'poin' => 2,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:39:07',
            ),
            9 => 
            array (
                'id_pelanggaran' => 36,
                'id_siswa' => 1849,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:40:10',
            ),
            10 => 
            array (
                'id_pelanggaran' => 37,
                'id_siswa' => 1849,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:40:11',
            ),
            11 => 
            array (
                'id_pelanggaran' => 38,
                'id_siswa' => 1849,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Tidak bawa buku',
                'poin' => 2,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:40:11',
            ),
            12 => 
            array (
                'id_pelanggaran' => 39,
                'id_siswa' => 1850,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Berkelahi',
                'poin' => 75,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:41:24',
            ),
            13 => 
            array (
                'id_pelanggaran' => 40,
                'id_siswa' => 1850,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Bolos Pelajaran',
                'poin' => 20,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:41:24',
            ),
            14 => 
            array (
                'id_pelanggaran' => 41,
                'id_siswa' => 1851,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Berkelahi',
                'poin' => 75,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:42:00',
            ),
            15 => 
            array (
                'id_pelanggaran' => 42,
                'id_siswa' => 1851,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Merokok',
                'poin' => 50,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:42:01',
            ),
            16 => 
            array (
                'id_pelanggaran' => 43,
                'id_siswa' => 1852,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:49:40',
            ),
            17 => 
            array (
                'id_pelanggaran' => 44,
                'id_siswa' => 1852,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Berkelahi',
                'poin' => 75,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:49:40',
            ),
            18 => 
            array (
                'id_pelanggaran' => 45,
                'id_siswa' => 1853,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Berkelahi',
                'poin' => 75,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:50:40',
            ),
            19 => 
            array (
                'id_pelanggaran' => 46,
                'id_siswa' => 1853,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Bolos Pelajaran',
                'poin' => 20,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:50:41',
            ),
            20 => 
            array (
                'id_pelanggaran' => 47,
                'id_siswa' => 1854,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Berkelahi',
                'poin' => 75,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:51:07',
            ),
            21 => 
            array (
                'id_pelanggaran' => 48,
                'id_siswa' => 1854,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Bolos Pelajaran',
                'poin' => 20,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:51:07',
            ),
            22 => 
            array (
                'id_pelanggaran' => 49,
                'id_siswa' => 1861,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:54:06',
            ),
            23 => 
            array (
                'id_pelanggaran' => 50,
                'id_siswa' => 1861,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:54:06',
            ),
            24 => 
            array (
                'id_pelanggaran' => 51,
                'id_siswa' => 1845,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:54:50',
            ),
            25 => 
            array (
                'id_pelanggaran' => 52,
                'id_siswa' => 1869,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:55:04',
            ),
            26 => 
            array (
                'id_pelanggaran' => 53,
                'id_siswa' => 1869,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:55:04',
            ),
            27 => 
            array (
                'id_pelanggaran' => 54,
                'id_siswa' => 1862,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Berkelahi',
                'poin' => 75,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:55:19',
            ),
            28 => 
            array (
                'id_pelanggaran' => 55,
                'id_siswa' => 1846,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:55:28',
            ),
            29 => 
            array (
                'id_pelanggaran' => 56,
                'id_siswa' => 1846,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:55:42',
            ),
            30 => 
            array (
                'id_pelanggaran' => 57,
                'id_siswa' => 1847,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 15:56:11',
            ),
            31 => 
            array (
                'id_pelanggaran' => 58,
                'id_siswa' => 1849,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:03:18',
            ),
            32 => 
            array (
                'id_pelanggaran' => 59,
                'id_siswa' => 1857,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:03:37',
            ),
            33 => 
            array (
                'id_pelanggaran' => 60,
                'id_siswa' => 1857,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:03:37',
            ),
            34 => 
            array (
                'id_pelanggaran' => 61,
                'id_siswa' => 1855,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:04:44',
            ),
            35 => 
            array (
                'id_pelanggaran' => 62,
                'id_siswa' => 1855,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:04:45',
            ),
            36 => 
            array (
                'id_pelanggaran' => 63,
                'id_siswa' => 1863,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:05:00',
            ),
            37 => 
            array (
                'id_pelanggaran' => 64,
                'id_siswa' => 1863,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:05:00',
            ),
            38 => 
            array (
                'id_pelanggaran' => 65,
                'id_siswa' => 1863,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Tidak bawa buku',
                'poin' => 2,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:05:01',
            ),
            39 => 
            array (
                'id_pelanggaran' => 66,
                'id_siswa' => 1864,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:05:28',
            ),
            40 => 
            array (
                'id_pelanggaran' => 67,
                'id_siswa' => 1864,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:05:29',
            ),
            41 => 
            array (
                'id_pelanggaran' => 68,
                'id_siswa' => 1848,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:13:28',
            ),
            42 => 
            array (
                'id_pelanggaran' => 69,
                'id_siswa' => 1846,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Tidak bawa buku',
                'poin' => 2,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:14:02',
            ),
            43 => 
            array (
                'id_pelanggaran' => 70,
                'id_siswa' => 1846,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Tidak bawa buku',
                'poin' => 2,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:14:10',
            ),
            44 => 
            array (
                'id_pelanggaran' => 71,
                'id_siswa' => 1865,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:17:43',
            ),
            45 => 
            array (
                'id_pelanggaran' => 72,
                'id_siswa' => 1865,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:17:43',
            ),
            46 => 
            array (
                'id_pelanggaran' => 73,
                'id_siswa' => 1870,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:17:55',
            ),
            47 => 
            array (
                'id_pelanggaran' => 74,
                'id_siswa' => 1870,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:17:55',
            ),
            48 => 
            array (
                'id_pelanggaran' => 75,
                'id_siswa' => 1858,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:18:14',
            ),
            49 => 
            array (
                'id_pelanggaran' => 76,
                'id_siswa' => 1858,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:18:15',
            ),
            50 => 
            array (
                'id_pelanggaran' => 77,
                'id_siswa' => 1871,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:19:18',
            ),
            51 => 
            array (
                'id_pelanggaran' => 78,
                'id_siswa' => 1871,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:19:32',
            ),
            52 => 
            array (
                'id_pelanggaran' => 79,
                'id_siswa' => 1871,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:19:33',
            ),
            53 => 
            array (
                'id_pelanggaran' => 80,
                'id_siswa' => 1872,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:19:47',
            ),
            54 => 
            array (
                'id_pelanggaran' => 81,
                'id_siswa' => 1872,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:19:47',
            ),
            55 => 
            array (
                'id_pelanggaran' => 82,
                'id_siswa' => 1872,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Tidak bawa buku',
                'poin' => 2,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:19:47',
            ),
            56 => 
            array (
                'id_pelanggaran' => 83,
                'id_siswa' => 1873,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:20:05',
            ),
            57 => 
            array (
                'id_pelanggaran' => 84,
                'id_siswa' => 1873,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:20:05',
            ),
            58 => 
            array (
                'id_pelanggaran' => 85,
                'id_siswa' => 1873,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Tidak bawa buku',
                'poin' => 2,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:20:06',
            ),
            59 => 
            array (
                'id_pelanggaran' => 86,
                'id_siswa' => 1874,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Terlambat',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:22:28',
            ),
            60 => 
            array (
                'id_pelanggaran' => 87,
                'id_siswa' => 1874,
                'tanggal' => '2026-02-22',
                'jenis_pelanggaran' => 'Atribut Tidak Lengkap',
                'poin' => 5,
                'keterangan' => NULL,
                'bukti_foto' => NULL,
                'dicatat_oleh' => 'saya josdun saya sehat',
                'created_at' => '2026-02-22 16:22:29',
            ),
        ));
        
        
    }
}