<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id_user' => 1,
                'namalengkap' => 'saya josdun saya sehat',
                'username' => '0606',
                'password' => '$2y$12$rhsqFAyo/V8IRxZEk9LLn.cyygBYDkTUYqYlxMwzEyMZB5BzqCfLS',
                'usertype' => 'admin',
                'foto' => 'profile-photos/zd9iAcwxfmjoO1pPNi90tEpfI38lgkbX6M2Q2trr.jpg',
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-05 04:43:56',
                'updated_at' => '2026-02-07 18:53:28',
            ),
            1 => 
            array (
                'id_user' => 47,
                'namalengkap' => 'Aded Fadly Mulyawan',
                'username' => '242510001',
                'password' => '$2y$12$K7lya4Bde9L9rxxccb36YuEBG6BIQR5mT9zOQwbfVjAAPcHnBe6.e',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:56',
                'updated_at' => '2026-02-21 17:11:56',
            ),
            2 => 
            array (
                'id_user' => 48,
                'namalengkap' => 'Adelia Nurul Aviyansah',
                'username' => '242510002',
                'password' => '$2y$12$epncuGytyGwB7m.8JeGAJu4CZbsTB/QJnRdKaboL8JQKVqYwhc9A.',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:56',
                'updated_at' => '2026-02-21 17:11:56',
            ),
            3 => 
            array (
                'id_user' => 49,
                'namalengkap' => 'Alan Rifki Saputra',
                'username' => '242510003',
                'password' => '$2y$12$J6Km1SJcrsTgpseo88u.xu2.Jpz29r6MG9jIGSntAmswLDD8s166i',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:56',
                'updated_at' => '2026-02-21 17:11:56',
            ),
            4 => 
            array (
                'id_user' => 50,
                'namalengkap' => 'Amelia Nur Maulida',
                'username' => '242510004',
                'password' => '$2y$12$KOTvc3u8WOiCPrng2p2ZseYAiUW81OqNs4u0foXzwjfe9.zRByTuG',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:56',
                'updated_at' => '2026-02-21 17:11:56',
            ),
            5 => 
            array (
                'id_user' => 51,
                'namalengkap' => 'Anggiesya Putri Hanuun',
                'username' => '242510005',
                'password' => '$2y$12$V856IvBy4JMLDulb.Wrh1.BM1ayFAoi2Q5wwm4ta0GD/exIaAFm8W',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:57',
                'updated_at' => '2026-02-21 17:11:57',
            ),
            6 => 
            array (
                'id_user' => 52,
                'namalengkap' => 'Anggun Cahya Kirani',
                'username' => '242510006',
                'password' => '$2y$12$7RRCszT5Tb66oUPZEm6L/O3zjt5TuiMRLz/yXNtQKVGYvCLk8RUc2',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:57',
                'updated_at' => '2026-02-21 17:11:57',
            ),
            7 => 
            array (
                'id_user' => 53,
                'namalengkap' => 'Arumy Prameswari',
                'username' => '242510007',
                'password' => '$2y$12$uQ8FqWY82l1XQrZj5C37zeuGUt0BqCSeXrk3hOdeJ9gEarGppkKpi',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:57',
                'updated_at' => '2026-02-21 17:11:57',
            ),
            8 => 
            array (
                'id_user' => 54,
                'namalengkap' => 'Aura Maulida Yassmin',
                'username' => '242510008',
                'password' => '$2y$12$KkXCGKhruUHY7UMO/UkD3uB1aFFCnIbAwdJSblMgCJKOK7ZO8ccq2',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:57',
                'updated_at' => '2026-02-21 17:11:57',
            ),
            9 => 
            array (
                'id_user' => 55,
                'namalengkap' => 'Ayuma Anayshfa',
                'username' => '242510009',
                'password' => '$2y$12$4iYSx3N6L4yc.Dzo0gWa9OwMu6pdzwTLxa6byo6N/DvbrEGj1dgZm',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:58',
                'updated_at' => '2026-02-21 17:11:58',
            ),
            10 => 
            array (
                'id_user' => 56,
                'namalengkap' => 'Daffi Alfahrizi',
                'username' => '242510010',
                'password' => '$2y$12$CaNuVCR.tSO8uphrWoweM.w5lOsur.s2o1hwyvoRx82KA.ubkdMYC',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:58',
                'updated_at' => '2026-02-21 17:11:58',
            ),
            11 => 
            array (
                'id_user' => 57,
                'namalengkap' => 'Daviero Ibnu Basid',
                'username' => '242510011',
                'password' => '$2y$12$mmPchfV8Gpmo/4LdPmiEeO6luFN/JCrGPjVpJYd.GM6n19BUjadS2',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:58',
                'updated_at' => '2026-02-21 17:11:58',
            ),
            12 => 
            array (
                'id_user' => 58,
                'namalengkap' => 'Difa Novita Sari',
                'username' => '242510012',
                'password' => '$2y$12$QQt6J/36N/zeWXl.sIsDl.MXzuLjj64x5ZLhDaBDxGX8Yv9UT/N5G',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:59',
                'updated_at' => '2026-02-21 17:11:59',
            ),
            13 => 
            array (
                'id_user' => 59,
                'namalengkap' => 'Dini Aprilia',
                'username' => '242510013',
                'password' => '$2y$12$.BExrQeckuOemP9R78PgXOlUbk7sePnjbA8MdbqDPPw3X2kUG8fu6',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:59',
                'updated_at' => '2026-02-21 17:11:59',
            ),
            14 => 
            array (
                'id_user' => 60,
                'namalengkap' => 'Dini Septia Ramadhani',
                'username' => '242510014',
                'password' => '$2y$12$GVDGp1.h8Q3TLbNGkJ3M2.eWSabqp/JojcCT9k/iriO/wBB4o/ZB.',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:59',
                'updated_at' => '2026-02-21 17:11:59',
            ),
            15 => 
            array (
                'id_user' => 61,
                'namalengkap' => 'Ghifari Gheria Saputra',
                'username' => '242510015',
                'password' => '$2y$12$Bk6WXhPqf3UA..VezIuKGeF9IB2pCxXmj2T6aOdhcXNP0/uuRrXeS',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:11:59',
                'updated_at' => '2026-02-21 17:11:59',
            ),
            16 => 
            array (
                'id_user' => 62,
                'namalengkap' => 'Keisya Rahma Nurfadilah',
                'username' => '242510016',
                'password' => '$2y$12$AeC6g48YcRer5Hy6edXOfeTVFdgUiJ90pBgBsnW7B2WKsHBu3Fo6.',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:00',
                'updated_at' => '2026-02-21 17:12:00',
            ),
            17 => 
            array (
                'id_user' => 63,
                'namalengkap' => 'Keyzha As Shiffa',
                'username' => '242510017',
                'password' => '$2y$12$l1wtNJZp/iHOOvXRJvNuTOocznfVYd4966NkRIXwrqom3/KyOcv2a',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:00',
                'updated_at' => '2026-02-21 17:12:00',
            ),
            18 => 
            array (
                'id_user' => 64,
                'namalengkap' => 'Laura Lidya Pratama',
                'username' => '242510018',
                'password' => '$2y$12$vjpFz1.b0jW8t4pyXulvZu09sYFkMk6NHiNAhPzerAMjC9/fCKwFC',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:00',
                'updated_at' => '2026-02-21 17:12:00',
            ),
            19 => 
            array (
                'id_user' => 65,
                'namalengkap' => 'Meisya Talaita Putri',
                'username' => '242510019',
                'password' => '$2y$12$9.Et60ST.HHZCJCYVmz/tOkzVgypxDeudIa9lIGp5dzZOyiTHSITy',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:00',
                'updated_at' => '2026-02-21 17:12:00',
            ),
            20 => 
            array (
                'id_user' => 66,
                'namalengkap' => 'Muhamad Syafiq Ramadhan',
                'username' => '242510020',
                'password' => '$2y$12$pXuwVRuA2VVSZqpj9Odm4.WFezKyZy/40P3LT0OdiYOhdutAgfBqi',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:01',
                'updated_at' => '2026-02-21 17:12:01',
            ),
            21 => 
            array (
                'id_user' => 67,
                'namalengkap' => 'Muhammad Al Ghifari T Zees',
                'username' => '242510021',
                'password' => '$2y$12$Ny97IrNdf7DCoQoFr7a2nOu0kDGzK5b3iPiT8vm21VIvasFGENNj2',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:01',
                'updated_at' => '2026-02-21 17:12:01',
            ),
            22 => 
            array (
                'id_user' => 68,
                'namalengkap' => 'Muhammad Rafiy Afandi',
                'username' => '242510022',
                'password' => '$2y$12$xQvM/5lOJgoE7QoLqzmgVukiqWae9q9qIgLe/JLb4/ecjBEEihV6i',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:01',
                'updated_at' => '2026-02-21 17:12:01',
            ),
            23 => 
            array (
                'id_user' => 69,
                'namalengkap' => 'Mustika',
                'username' => '242510023',
                'password' => '$2y$12$qeX4EAG/vKmNFYAUYjt2meTXHd0aj5rFZ3sw9oRpFwBCTAbLveF1q',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:01',
                'updated_at' => '2026-02-21 17:12:01',
            ),
            24 => 
            array (
                'id_user' => 70,
                'namalengkap' => 'Nayla Salwa Ramadhani',
                'username' => '242510024',
                'password' => '$2y$12$fAsK6t3sqWMNkOvSzO3NteLkrxJUjZRrJ72L0l3Sg6l8p1X2erS32',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:02',
                'updated_at' => '2026-02-21 17:12:02',
            ),
            25 => 
            array (
                'id_user' => 71,
                'namalengkap' => 'Non Ayu Sandra',
                'username' => '242510025',
                'password' => '$2y$12$l6eBqVrbexG7p/5MiR.eousD8TCuE59ep08D4/4a6aFNA1Nk3dsHm',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:02',
                'updated_at' => '2026-02-21 17:12:02',
            ),
            26 => 
            array (
                'id_user' => 72,
                'namalengkap' => 'Putra Bagus Setiawan',
                'username' => '242510026',
                'password' => '$2y$12$SUQ3mu.bOfB3VdhUC4Am6eDv5TCTJw61jSYAC68Ncw1zcQ8tl6agK',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:02',
                'updated_at' => '2026-02-21 17:12:02',
            ),
            27 => 
            array (
                'id_user' => 73,
                'namalengkap' => 'Putri Soleha',
                'username' => '242510027',
                'password' => '$2y$12$8EaSXlyLW8sJAy489rQCB.H9OScumzMj4pyu3am90Yq.eoxAK5wbS',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:02',
                'updated_at' => '2026-02-21 17:12:02',
            ),
            28 => 
            array (
                'id_user' => 74,
                'namalengkap' => 'Safa Nurairin',
                'username' => '242510028',
                'password' => '$2y$12$0jUJyP15pMivW4ootbKWiedJMNearDux4pBrApvSUgbAg8foYGquy',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:03',
                'updated_at' => '2026-02-21 17:12:03',
            ),
            29 => 
            array (
                'id_user' => 75,
                'namalengkap' => 'Salsa Novita Sari',
                'username' => '242510029',
                'password' => '$2y$12$SFM4qWuFBBADLnZOV467deY1uYEQFVy2ekU41rIEyfoYcBsWDJmb.',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:03',
                'updated_at' => '2026-02-21 17:12:03',
            ),
            30 => 
            array (
                'id_user' => 76,
                'namalengkap' => 'Syahla Syaqila Sopanudin',
                'username' => '242510030',
                'password' => '$2y$12$7nyRn4mtW5TQxok7SPGsDOARtgICmuyfLWmJZ6i1lAg6WNn9f.GAC',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:03',
                'updated_at' => '2026-02-21 17:12:03',
            ),
            31 => 
            array (
                'id_user' => 77,
                'namalengkap' => 'Wina Sahara',
                'username' => '242510031',
                'password' => '$2y$12$PzgjcHoUigJok1TMP1C/oOGgcV0bS.SlGZln4wSIDD8zqQe/D4Hx.',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:03',
                'updated_at' => '2026-02-21 17:12:03',
            ),
            32 => 
            array (
                'id_user' => 78,
                'namalengkap' => 'Windy Febriyanakasih',
                'username' => '242510032',
                'password' => '$2y$12$BqzpWp9rZS624WunZrjeBOiO8nZRrcG/uYC9FSUNwOw.nC3idtNh6',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:04',
                'updated_at' => '2026-02-21 17:12:04',
            ),
            33 => 
            array (
                'id_user' => 79,
                'namalengkap' => 'Zidhan Choiru Saleh',
                'username' => '242510033',
                'password' => '$2y$12$5SXCcbi9q/fwvQALcV0WReAHkM49n7o8tLuzFPTU.6DgyDIoP2hym',
                'usertype' => 'siswa',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => NULL,
                'created_at' => '2026-02-21 17:12:04',
                'updated_at' => '2026-02-21 17:12:04',
            ),
            34 => 
            array (
                'id_user' => 80,
                'namalengkap' => 'Aku Siapa Ya',
                'username' => '1234',
                'password' => '$2y$12$FeQ2uwtsjUH/5kB/1hV0EOLjvI/xm2WKHJ7/uGt2niowUM5G4l6Ry',
                'usertype' => 'walas',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => 'dqyjQ8Q3UEtmZxeXFALAvH:APA91bExd5tYbClJ5zc-_5y1M9roS9Ep24Ah9RYkBohAsl7kpsVAYAnp03etq_Uo4TbNULuUhBLbanOLon-RvIC3vvWDVcykhaOTymCuFWhefYFbtWZJ1B8',
                'created_at' => '2026-02-22 11:35:26',
                'updated_at' => '2026-02-22 16:19:11',
            ),
            35 => 
            array (
                'id_user' => 81,
                'namalengkap' => 'Katanya Ini Akun Josdun',
                'username' => '12345',
                'password' => '$2y$12$adqghOOrG53Nx98TJVQJqOyE1RRFMyagspnIqJyIbnzWQ/gkzArt2',
                'usertype' => 'bk',
                'foto' => NULL,
                'status' => 'aktif',
                'remember_token' => NULL,
                'fcm_token' => 'c_KBNPPZP7FlDchHeT_INH:APA91bF_CIXl4fP_LIhLfAq-VKi1NiNtYHLnDriMOCsHfq0zH7b26zcprVBxry8HPlNvDhncE7n6ymL1LPQVIBpinsFneg_fMzZb8eMPIgpCVV4oD87nNFI',
                'created_at' => '2026-02-22 11:36:17',
                'updated_at' => '2026-02-22 15:49:00',
            ),
        ));
        
        
    }
}